### ISSUE TITLE
example

### ISSUE THREAD

**Issue by dynamitemedia** [JoshyFrancis/php_background_process#1]
im sorry  i am confused how to use this...

do you have any examples and instructions?

will this run a .php  webpage every so often? similar to a cron job?

**Comment by JoshyFrancis** [comment]
Please run the background_process.php file. In windows, you may have to set up the php executable path in the code. It is not like cron job, but you can re call the same process or command again in a specified interval thus you can make a schedule. I have made an email sending program that runs background with this class. Both procedural and object-oriented methods are given.

**Comment by JoshyFrancis** [comment]
One example, Procedural way.
```

					$cmd='';
					if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {//'This is a server using Windows!';
						 $cmd=  $php_path.'\php.exe '.$path.'\long_process.php' ;	
					}else{
						$cmd='/usr/bin/php -f  /var/www/example.com/public/long_process.php';
					}
                                       $pid=run_process($cmd);
                                          if(is_process_running($pid)){
						echo 'Process running';
                                                stop_process($pid);
					}else{
						echo 'Process not running';
					}

```
